-- Supabase schema for Realtime Pixel Painter
-- Rolling cooldown: max 5 paints in the last 1 minute.

create table if not exists public.pixel_cells (
  x integer not null check (x >= 0 and x < 64),
  y integer not null check (y >= 0 and y < 64),
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  updated_by uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint pixel_cells_pkey primary key (x, y)
);

create table if not exists public.pixel_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  x integer not null check (x >= 0 and x < 64),
  y integer not null check (y >= 0 and y < 64),
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  created_at timestamptz not null default now()
);

create index if not exists pixel_events_user_created_at_idx
  on public.pixel_events (user_id, created_at desc);

alter table public.pixel_cells enable row level security;
alter table public.pixel_events enable row level security;

-- Read policies for authenticated users.
drop policy if exists "pixel_cells_select_authenticated" on public.pixel_cells;
create policy "pixel_cells_select_authenticated"
  on public.pixel_cells
  for select
  to authenticated
  using (true);

drop policy if exists "pixel_events_select_own" on public.pixel_events;
create policy "pixel_events_select_own"
  on public.pixel_events
  for select
  to authenticated
  using (auth.uid() = user_id);

-- No direct write policies by design.
drop policy if exists "pixel_cells_insert_none" on public.pixel_cells;
create policy "pixel_cells_insert_none"
  on public.pixel_cells
  for insert
  to authenticated
  with check (false);

drop policy if exists "pixel_cells_update_none" on public.pixel_cells;
create policy "pixel_cells_update_none"
  on public.pixel_cells
  for update
  to authenticated
  using (false)
  with check (false);

drop policy if exists "pixel_events_insert_none" on public.pixel_events;
create policy "pixel_events_insert_none"
  on public.pixel_events
  for insert
  to authenticated
  with check (false);

create or replace function public.place_pixel(p_x integer, p_y integer, p_color text)
returns table (
  success boolean,
  remaining_paints integer,
  next_available_at timestamptz,
  error text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_recent_count integer;
  v_oldest_in_window timestamptz;
begin
  if v_user_id is null then
    return query select false, 0, null::timestamptz, 'Not authenticated'::text;
    return;
  end if;

  if p_x < 0 or p_x >= 64 or p_y < 0 or p_y >= 64 then
    return query select false, 0, null::timestamptz, 'Pixel out of bounds'::text;
    return;
  end if;

  if p_color !~ '^#[0-9A-Fa-f]{6}$' then
    return query select false, 0, null::timestamptz, 'Invalid color format'::text;
    return;
  end if;

  select count(*), min(created_at)
  into v_recent_count, v_oldest_in_window
  from public.pixel_events
  where user_id = v_user_id
    and created_at > (v_now - interval '1 minute');

  if v_recent_count >= 5 then
    return query select false, 0, v_oldest_in_window + interval '1 minute', 'Cooldown exceeded'::text;
    return;
  end if;

  insert into public.pixel_events (user_id, x, y, color)
  values (v_user_id, p_x, p_y, upper(p_color));

  insert into public.pixel_cells (x, y, color, updated_by, updated_at)
  values (p_x, p_y, upper(p_color), v_user_id, v_now)
  on conflict (x, y)
  do update set
    color = excluded.color,
    updated_by = excluded.updated_by,
    updated_at = excluded.updated_at;

  select count(*), min(created_at)
  into v_recent_count, v_oldest_in_window
  from public.pixel_events
  where user_id = v_user_id
    and created_at > (v_now - interval '1 minute');

  return query
  select
    true,
    greatest(0, 5 - v_recent_count),
    case when v_recent_count >= 5 then v_oldest_in_window + interval '1 minute' else v_now end,
    null::text;
end;
$$;

revoke all on function public.place_pixel(integer, integer, text) from public;
grant execute on function public.place_pixel(integer, integer, text) to authenticated;

-- Enable Supabase Realtime on pixel_cells in your project dashboard:
-- Database -> Replication -> Add `public.pixel_cells` to `supabase_realtime` publication.
